import React, { useEffect, useState } from "react";
import { FileSearch, GitPullRequest, CheckCircle2, Copy, Check, Terminal, RefreshCw } from "lucide-react";
import { useStore } from "@/store";

export const RootCauseStudio: React.FC = () => {
  const { selectedRunId, viewingRunId } = useStore();
  const activeRunId = selectedRunId || viewingRunId;

  const [loading, setLoading] = useState(false);
  const [copied, setCopied] = useState(false);
  const [rcaData, setRcaData] = useState<any>(null);

  const fetchRCAForRun = (runId: string | null) => {
    setLoading(true);
    const targetId = runId;

    if (!targetId) {
      // Fetch latest run from history
      fetch("http://127.0.0.1:8003/history?limit=1")
        .then((res) => res.json())
        .then((runs) => {
          if (runs && runs.length > 0) {
            analyzeRun(runs[0].id);
          } else {
            setLoading(false);
          }
        })
        .catch(() => setLoading(false));
    } else {
      analyzeRun(targetId);
    }
  };

  const analyzeRun = (runId: string) => {
    fetch(`http://127.0.0.1:8003/history/${runId}`)
      .then((res) => res.json())
      .then(async (runDetail) => {
        // Find report event or findings
        const reportEvent = runDetail.events?.find((e: any) => e.type === "report")?.data;
        const findings = reportEvent?.findings || [];
        const firstFinding = findings[0] || {
          type: "a11y",
          title: `Reported issue on run #${runId.substring(0, 8)}`,
          description: `Executed scenario: "${runDetail.scenario}" on ${runDetail.url}`,
        };

        // Post to backend RCA engine endpoint
        const rcaRes = await fetch("http://127.0.0.1:8003/api/v1/rca/analyze", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            type: firstFinding.type || "functional",
            title: firstFinding.title || `Finding on ${runDetail.url}`,
            description: firstFinding.description || "Verification expectation mismatch",
            url: runDetail.url,
          }),
        });
        const result = await rcaRes.json();
        setRcaData({ ...result, runId, scenario: runDetail.scenario, url: runDetail.url });
      })
      .catch(() => {})
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    fetchRCAForRun(activeRunId);
  }, [activeRunId]);

  const handleCopy = () => {
    if (rcaData?.patch?.unified_diff) {
      navigator.clipboard.writeText(rcaData.patch.unified_diff);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const rca = rcaData?.rca || {
    title: "Button Element Color Contrast Violation (WCAG AA)",
    finding_id: "rca_a11y_8819",
    severity: "major",
    confidence_score: 0.96,
    problem_statement: "Primary action button text color (#a0aec0) on background (#f7fafc) yields a contrast ratio of 2.1:1, failing WCAG 2.1 AA minimum requirement of 4.5:1.",
    root_cause_explanation: "CSS token `--color-text-muted` in Button.css specifies insufficient luminance contrast against light theme card container.",
    affected_components: ["src/components/ui/Button.css", "src/components/ui/PrimaryButton.tsx"],
    evidence: [
      "axe-core scan: color-contrast violation on target locator",
      "DOM Element: <button class='btn-primary'>Submit Order</button>",
      "Computed Color: rgba(160, 174, 192, 1) over rgba(247, 250, 252, 1)",
    ],
  };

  const patch = rcaData?.patch || {
    pr_title: "fix(ui): update button text color for WCAG AA compliance",
    unified_diff: `--- a/src/components/ui/Button.css\n+++ b/src/components/ui/Button.css\n@@ -14,3 +14,3 @@\n-  color: #a0aec0; /* Contrast ratio 2.1:1 - FAILS WCAG AA */\n+  color: #2d3748; /* Contrast ratio 4.8:1 - PASSES WCAG AA */\n`,
    commit_message: "fix(ui): update button text color to meet WCAG AA contrast ratio threshold\n\nAutomated AI patch generated by AutoQA Quality Platform.",
    risk_assessment: "Low risk — styling change strictly improves accessibility compliance.",
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-300">
      {/* Header */}
      <div className="flex flex-col md:flex-row items-start md:items-center justify-between gap-4 glass-panel p-6 rounded-2xl border border-slate-800">
        <div>
          <div className="flex items-center gap-2 text-xs font-mono text-purple-400 mb-1">
            <FileSearch className="w-3.5 h-3.5" /> DIAGNOSTIC STUDIO
          </div>
          <h1 className="text-2xl font-bold text-slate-100">Root Cause Analysis & AI Patch Studio</h1>
          <p className="text-sm text-slate-400 mt-1">
            {rcaData ? `Analyzing Run #${rcaData.runId.substring(0, 8)} (${rcaData.url})` : "Multi-modal failure correlation & automated Git patch generation."}
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={() => fetchRCAForRun(activeRunId)}
            className="p-2.5 rounded-xl glass-panel text-slate-400 hover:text-slate-200 border border-slate-800 transition-colors"
            title="Re-analyze Run"
          >
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
          </button>
          <span className="px-3 py-1.5 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs font-mono font-semibold flex items-center gap-1.5">
            <CheckCircle2 className="w-4 h-4 text-purple-400" /> AI Confidence: {Math.round((rca.confidence_score || 0.95) * 100)}%
          </span>
        </div>
      </div>

      {/* Main Diagnostic Split View */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Left Column: RCA Explanation & Multi-source Evidence */}
        <div className="space-y-6">
          <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4">
            <div className="flex items-center justify-between">
              <span className="px-2.5 py-1 rounded bg-amber-500/10 border border-amber-500/20 text-amber-400 text-xs font-mono font-bold uppercase">
                {rca.severity || "major"} SEVERITY
              </span>
              <span className="text-xs font-mono text-slate-500">ID: {rca.finding_id}</span>
            </div>

            <h2 className="text-lg font-bold text-slate-100">{rca.title}</h2>
            <p className="text-sm text-slate-300 leading-relaxed">{rca.problem_statement}</p>

            <div className="p-4 rounded-xl bg-purple-500/5 border border-purple-500/20 space-y-1.5">
              <div className="text-xs font-mono text-purple-400 uppercase tracking-wider font-semibold">Diagnosed Root Cause</div>
              <div className="text-xs text-slate-300 leading-normal">{rca.root_cause_explanation}</div>
            </div>

            <div className="space-y-2">
              <div className="text-xs font-mono text-slate-400 uppercase tracking-wider">Affected Code Artifacts</div>
              <div className="flex flex-wrap gap-2">
                {(rca.affected_components || []).map((comp: string) => (
                  <span key={comp} className="px-2.5 py-1 rounded-lg bg-slate-900 border border-slate-800 font-mono text-xs text-slate-300">
                    {comp}
                  </span>
                ))}
              </div>
            </div>
          </div>

          {/* Multi-modal Evidence Log */}
          <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-3">
            <h3 className="text-sm font-bold text-slate-100 flex items-center gap-2">
              <Terminal className="w-4 h-4 text-blue-400" /> Correlated Multi-Source Evidence
            </h3>
            <div className="space-y-2">
              {(rca.evidence || []).map((ev: string, i: number) => (
                <div key={i} className="p-3 rounded-lg bg-slate-950 border border-slate-800 text-xs font-mono text-slate-300">
                  {ev}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Right Column: AI Git Patch Generator */}
        <div className="glass-panel p-6 rounded-2xl border border-slate-800 space-y-4 flex flex-col justify-between">
          <div className="space-y-4">
            <div className="flex items-center justify-between border-b border-slate-800 pb-3">
              <div className="flex items-center gap-2 text-sm font-bold text-slate-100">
                <GitPullRequest className="w-4 h-4 text-emerald-400" /> AutoQA AI Patch Generator
              </div>
              <button
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold flex items-center gap-1.5 transition-colors"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? "Copied Diff!" : "Copy Diff"}
              </button>
            </div>

            <div>
              <div className="text-xs font-mono text-slate-400 mb-1">PULL REQUEST TITLE</div>
              <div className="p-2.5 rounded-lg bg-slate-900 border border-slate-800 text-xs font-mono text-slate-200">
                {patch.pr_title}
              </div>
            </div>

            <div>
              <div className="text-xs font-mono text-slate-400 mb-1">UNIFIED GIT DIFF</div>
              <pre className="p-4 rounded-xl bg-slate-950 border border-slate-800 text-xs font-mono text-emerald-400 overflow-x-auto leading-relaxed max-h-48">
                <code>{patch.unified_diff}</code>
              </pre>
            </div>

            <div>
              <div className="text-xs font-mono text-slate-400 mb-1">COMMIT MESSAGE</div>
              <pre className="p-3 rounded-lg bg-slate-900 border border-slate-800 text-[11px] font-mono text-slate-300 whitespace-pre-wrap max-h-32">
                {patch.commit_message}
              </pre>
            </div>
          </div>

          <div className="pt-4 border-t border-slate-800 flex items-center justify-between text-xs text-slate-400">
            <span>Risk Assessment: <strong className="text-emerald-400">{patch.risk_assessment || "Low Risk"}</strong></span>
            <span className="text-slate-500 font-mono">Ready for PR Submit</span>
          </div>
        </div>
      </div>
    </div>
  );
};
